flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12.3
- skylighting-0.12.3
- emojis-0.1.2
- lpeg-1.0.3
- hslua-2.2.0
- hslua-aeson-2.2.0
- hslua-classes-2.2.0
- hslua-core-2.2.0
- hslua-marshalling-2.2.0
- hslua-module-doclayout-1.0.4
- hslua-module-path-1.0.2
- hslua-module-system-1.0.2
- hslua-module-text-1.0.2
- hslua-module-version-1.0.2
- hslua-objectorientation-2.2.0
- hslua-packaging-2.2.0
- lua-2.2.0
- lua-arbitrary-1.0.1
- tasty-hslua-1.0.2
- tasty-lua-1.0.2
- pandoc-lua-marshal-0.1.5.1
- aeson-pretty-0.8.9
- unicode-transforms-0.4.0.1
- unicode-data-0.3.0
- commonmark-pandoc-0.2.1.2
- ipynb-0.2
- pandoc-types-1.22.2
- texmath-0.12.5
- citeproc-0.7
- commonmark-0.2.2
- commonmark-extensions-0.2.3.1
- doclayout-0.4
- doctemplates-0.10.0.2
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]
