categories: 					Themes
search: Search
tags: 							Topics
tagcloud: 					Topics Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: 						History
archive_b: "						History: %s"
page: Page %d
recent_posts: 					Latest
newer: Newer
older: Older
share: Share
powered_by: Powered by
rss_feed: RSS Feed
category: Category
tag: Tag