title:		"Gary B. Genett"
subtitle:	
description:	A collection of all things Gary B. Genett
author:		Gary B. Genett
language:	en
timezone:	US/Pacific

url:		http://www.garybgenett.net
root:		/
permalink:	:year/:month/:day/:title/
date_format:	YYYY-MM-DD
time_format:	HH:mm:ss
per_page:	10

theme:		landscape
#WORKING:NOW source_dir:	/.g/_data/zactive/writing/garybgenett
#WORKING:NOW public_dir:	/.g/_data/zactive/writing/garybgenett/.public
skip_render: 
	- CNAME 
	- Gary_B_Genett** 
	- resume** 
	- resume/**

sitemap:
	path:	/sitemap.xml

feed:
	path:	/atom.xml
	type:	atom
	limit:	10

deploy:
	repo:	git@github.com:garybgenett/www.garybgenett.net.git
	type:	git
